# title: Clint Monroe
# logo: /assets/img/headshot.jpg
# description: text below image
# show_downloads: true
# theme: jekyll-theme-minimal

# Site settings
title: Clint Monroe's Portfolio
subtitle: Showcasing my work and projects
description: >
  Welcome to my portfolio! Here, you'll find details about my projects, professional experiences, and technical skills.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://clintmonroe00.github.io" # your GitHub Pages URL or custom domain

# Theme settings
theme: lanyon

# Sidebar settings
sidebar:
  - Home
  - About
  - Projects
  - Blog
  - Contact

# Author information
author:
  name: Clint Monroe
  email: clintmonroe00@gmail.com.com
  github: clintmonroe00
  linkedin: clint-monroe

# Social links (optional)
social_links:
  - name: GitHub
    url: https://github.com/clintmonroe00
  - name: LinkedIn
    url: https://linkedin.com/in/clint-monroe
  - name: Email
    url: mailto:clintmonroe00@gmail.com.com

# Plugins (optional, for advanced functionality)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Other configurations
permalink: pretty
show_downloads: true
