title: CS-499 Computer Science Capstone
description: My capstone project portfolio, showcasing technical artifacts and enhancements.
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
